-- -- ====================================================
-- -- 3️⃣ Silver table - parse VARIANT safely (triple-encoded JSON)
-- -- ====================================================

-- -- Create the Silver table
-- CREATE OR REFRESH STREAMING TABLE silver_events_patient_data
-- (
--   ID STRING,
--   Shard STRING,
--   Private STRING,
--   Name STRING,
--   Address1 STRING,
--   Address2 STRING,
--   City STRING,
--   State STRING,
--   ZipCode STRING,
--   Country STRING,
--   PhoneNumber STRING,
--   BusinessID STRING,
--   Created STRING,
--   CreatedBy STRING,
--   Updated STRING,
--   UpdatedBy STRING,

--   -- Parsed VARIANT columns
--   D_variant VARIANT,
--   P_variant VARIANT,
--   V_variant VARIANT,

--   processedTime TIMESTAMP
-- )
-- TBLPROPERTIES (
--   'delta.enableChangeDataFeed' = 'true',
--   'delta.enableDeletionVectors' = 'true',
--   'delta.enableRowTracking' = 'true',
--   'delta.feature.variantType-preview' = 'supported',
--   'quality' = 'silver'
-- );

-- -- CDC Flow to populate the Silver table
-- CREATE FLOW silver_events_patient_data_cdc AS AUTO CDC INTO
--   silver_events_patient_data
-- FROM (
--   SELECT
--     ID,
--     Shard,
--     Private,
--     Name,
--     Address1,
--     Address2,
--     City,
--     State,
--     ZipCode,
--     Country,
--     PhoneNumber,
--     BusinessID,
--     Created,
--     CreatedBy,
--     Updated,
--     UpdatedBy,
--     current_timestamp() AS processedTime,
--     _change_type, _commit_version, _commit_timestamp
--   FROM (
--     FROM STREAM(patient_cdf)
--     SELECT *
--   )
-- )
-- KEYS (ID, BusinessID)
-- APPLY AS DELETE WHEN _change_type = "delete"
-- APPLY AS TRUNCATE WHEN _change_type = "truncate"
-- SEQUENCE BY (_commit_version, _commit_timestamp)
-- COLUMNS * EXCEPT (_change_type, _commit_version, _commit_timestamp)
-- STORED AS SCD TYPE 1;